### PR TITLE
Add time unit and max value to session timeout

### PR DESCRIPTION
**Pull request by deajan**

### CODE REVIEW

**Comment by nuxsmin** [comment]
Hello, please see my comment on #1122 

Regards

**Comment by deajan** [comment]
I think you meant #1080 ?

**Comment by nuxsmin** [comment]
Sorry, you're right. Anyway, I've added the time unit within the tooltip.

I'm not closing your PRs because I prefer to do it for myself, it's only about some modifications would be needed, for example, max time should be set as a formatted string ('Timeout (seconds, max %d)'), so I don't want to bother you about these practices.

I'd like to write down a brief documentation about coding style, so anyone could follow some simple rules to make good contributions (I'm not telling your aren't...) which can be suitable for multiple purposes.

Thanks for your contribution!

**Comment by vmario89** [comment]
Hey @nuxsmin ,
thanks for that. Some guidelines for contribution are good. 

By the way i know that i do not always stick to the guidelines which are presented in the prefilled issue context. So the contributions i do are most times a wild mixture and not best fitting to some general guidelines :-D I am more the visual guy. A screenshot or 2 or 3, some markup and some log line tells more than a bunch of different static text blocks in my eyes. I always have the user and the dev perspective in mind because i am also a user who looks in closed tickets to find some good old information to a certain topic ;-)

regards and have a nice evening, Mario

**Comment by nuxsmin** [comment]
Sure @vmario89 , guidelines are there for those users who start writing issues without any concerns about who is reading them, so sometimes strictness should be applied. Of course, you aren't like them, and pictures are better than words.

Nice evening too!

**Pull request closed without merging**
