### PR TITLE
Installation in cluster mode and not just on localhost

### PR DESCRIPTION
**Pull request by Fernand0S**
When installing in cluster mode it was not possible, as the file limited its use to local mode only.

### CODE REVIEW

**Review by Fernand0S — COMMENTED** [review]
The installer.php file only mentions installation in local mode and not in cluster mode. changing the variables it is possible to perform the installation in cluster mode.

**Comment by Fernand0S** [comment]
The installer.php file only mentions installation in local mode and not in cluster mode. changing the variables it is possible to perform the installation in cluster mode.

**Review by Fernand0S — COMMENTED** [review]
The values ​​from false to true were modified as cluster mode installation was not possible.

Modifying the value of localhost to accept connection in cluster mode with the value changed to %

**Comment by Fernand0S** [comment]
The values ​​from false to true were modified as cluster mode installation was not possible.

Modifying the value of localhost to accept connection in cluster mode with the value changed to %

**Comment by nuxsmin** [comment]
Hello,

thanks for your contribution!

Regarding the cluster installation, I'm not sure about the meaning of "cluster", since sysPass is not intended to be run in a cluster mode (ie. several instances serving content at the same time), though it could be run using multiple replicas (that isn't clustering), but some drawbacks need to be addressed like session  and configuration sharing.

I you are trying to run sysPass in a Pacemaker cluster (eg. active-pasive mode) you would need to create a dedicated database user, set the host to `%` and use the hosting mode while installing.

sysPass is a security tool and it should let the user to set the desired security level, so it won't include any configuration that will lower the security level.

Regards.

**Comment by Fernand0S** [comment]
Installation in cluster mode I say to use the tool, if you are using Docker Swarm, since in this mode Swarm has different networks for connectivity, so when the installation is started: application makes the request to the db and goes to create the user sp_xxxxx, but when the database returns it does not come through the same network do you understand now the error that the tool has?

**Pull request closed without merging**
