### PR TITLE
Fix for #1122

### PR DESCRIPTION
**Pull request by deajan**

### CODE REVIEW

**Comment by nuxsmin** [comment]
Hello, thanks (again) for your contribution!!

You may wonder why I don't add such 'hints'/'tips'...It's a matter of translations, since every modified string will break the current translation for every language (when Spanish was set as base language, it was a really pain...), so I decided to think twice before breaking a translation and try out other ways to get it like either help/warn icons, documentation, etc..What do you think?

Regards

**Comment by vmario89** [comment]
Hi @nuxsmin,
breaking the translations is right. But i think a clean concept is to fix/keep clean the lang sources only and apply corrected string to each translation language with each release. I know that it makes more work. But it keeps other languages more correct too. Doing it vice versa is a nasty workaround. English as base language is really good because most because understand english in a common sense. All translations are just making sysPass better but not perfect if the source looks not straight forward. 

I think in the case of #1122 there is no string change in my eyes - the warning message itself is correct. There is only missing a hint that the user has to enter the bind password again. You also just could empty the password field - so the user can see that there is no input in the field.

By the way:
I think it would be good to have some "call for translations" every release so people can add their translations into POEditor web platform. At the moment i see that some people use poedit to upload po/mo files manually with a pull request (as i did before). If you make some change in sysPass i do not recognize language changes. I only see them because i log me in into poeditor frequently. If the translation is not 100% i am looking for missing string translations.

And by the way i am interested how many contributors for languages are out there. As is know there is active work on spanish/english/french. What's with the other languages? Means: if there are only less languages are maintained it does not break that much when changing some source string.

regards, Mario

**Comment by nuxsmin** [comment]
@vmario89 I agree with both comments, and I'm not telling to not make these modifications, I'm just thinking what would be the "better" way to add more context to a feature, that is either modifying the string itself or adding some useful help.

> I think it would be good to have some "call for translations" every release so people can add their translations into POEditor web platform. At the moment i see that some people use poedit to upload po/mo files manually with a pull request (as i did before). If you make some change in sysPass i do not recognize language changes. I only see them because i log me in into poeditor frequently. If the translation is not 100% i am looking for missing string translations.

Sure, but I don't want to bother you sending several "call for translations", so once code tweaks get finished, I'd rather make the call ;)

**Comment by nuxsmin** [comment]
Warning icon and notice were added.

**Pull request closed without merging**
