### PR TITLE
* [MOD] Fixes German I18N

### PR DESCRIPTION
**Pull request by Andi-fr**
Makes german I18N more precisely

### CODE REVIEW

**Comment by nuxsmin** [comment]
Hello @Andi-fr 

firstly, thank you for your contribution!!

I've noticed that you changed the translation for "Customer/Client" which has been translated to "Area/Department" ("Bereiche" in German), is that right?

Kind Regards

**Comment by W4rlock34** [comment]
Hello @Andi-fr and @nuxsmin ,

i wouldn´t say that this is the correct translation (refering to the english translation).
The only change i see in `messages.po` is that the translation of "Customer" was changed from "Kunde" to "Bereich", which is not correct. "Customer" translates to "Kunde" in german.

When i edit an account i see two dropdown fields (Customer and Category), so if you would replace "Kunde" with "Bereich" this two fields would be Area and Category.
If you want to refeer on "Departement" you should use "Abteilung" in german.

I don´t know which changes were made to `messages.mo`, so i can´t help with that one.
But apart from that i don´t really see the point of a Customer field, isn´t it clear that me or my company is the customer? Or is already the english translation wrong?

Kind regards

**Comment by Andi-fr** [comment]
I am pretty sure the english translation has mistakes. I tried to give the
'faulty' english I18N some sense.

2017-08-10 11:21 GMT+02:00 Oliver Winkler <notifications@github.com>:

**Comment by nuxsmin** [comment]
@W4rlock34 and @Andi-fr you're right since "Customer/Client" wouldn't fit on every installation, and that is so because sysPass was originally built to store customers/clients passwords. I work for an IT company so our customers/clients connection data are stored in sysPass, although our internal data owns to the company itself, we name it as a customer/client/.

You may think that it does not fit your requirements, but it's hard to develop an universal application in which every meaning fits your organization structure, so you could either treat this field as "Department/Bereich" or fork sysPass project to make those changes.

I would use the following syntax for naming departments: YOUR_COMPANY_NAME/DEPARTMENT so "Kunde" would make sense.

Kind regards

**Pull request closed without merging**
