### PR TITLE
Azure patch

### PR DESCRIPTION
**Pull request by deajan**
This patch resolves our discussion about #1050 by implementing the disabled and empty password user account filters again, but this time with a nice AD Azure option that allows them to be disabled.

### CODE REVIEW

**Comment by deajan** [comment]
Translations missing btw... I can do the french and german ones.

**Comment by nuxsmin** [comment]
Hello, thanks for your contribution!. I'm sightly disagree with this implementation, since newer LDAP implementations should be in a separate class (eg. LdapAzureAd), so all the related code for it won't be mixed in an existing implementation, thus no `if`/`else` statements are needed.

The drawback would be code duplication, but taking into account future changes on each implementation (MsAds vs AzureAd), it could be a minor issue.

What do you think?

Regards

**Comment by deajan** [comment]
IMHO, MSAD and Azure are the same beasts, hence the SyncAD tool to make them work togheter, the only difference being the userAccountControl which does not exist on Azure because of the nature of cloud billing all existing accounts.

I don't think Microsoft will ever make bigger differences between both implementations, one is supposed to be able to swap from AD to Azure.

So I think it's okay to keep the Azure AD implementation with the standard AD implementation.
Maybe there's a better way to have the const defined in an if / else statement, so it will be the only line that differentiates both codes.

**Comment by deajan** [comment]
Closing this since you've done your implementation.

**Pull request closed without merging**
