### PR TITLE
New Feature: Add logging to Syslog for fail2ban to block offending clients

### PR DESCRIPTION
**Pull request by wendelb**
Hi,

I found sysPASS on my search for an on-premise secure password storage and find it quite useful and fitting. There is one feature that I find missing: Since I want do put the software on a public facing host, I want to block clients with too many failed password attempts using fail2ban.
Here is a full implementation of it, complete with an option in the settings menu, Since I haven't worked with gettext before, here are the English and German translation for the two new language keys: https://gist.github.com/wendelb/252727936e62801e631b7fb1fe8cb06f

For fail2ban to work, the configuration needs to be ammended. All needed new files are here: https://gist.github.com/wendelb/090f219dd151225d2c8e83763873d7a5 - You might want to put them on the wiki.

There isn't much for documentation. Once the new switch is enabled, failed login attempts will be reported to syslog and written to `/var/log/auth.log` (depending on your platform and configuration).

Kind regards
Bernhard Wendel

### CODE REVIEW

**Comment by nuxsmin** [comment]
Hello, 

Thanks so much for your support and contribution.

I'll need to review you push request and think about how to implement it in the next release, because the 1.2 version is closed to new features, it'll only receive bug fixes or security fixes.

In the next release (1.3 at the devel branch ) there will be some new features like syslogging by using CEF format, so you'll be able to use SIEM frameworks to trigger actions based on events.

I'll implement your contribution on the devel branch.

Kind regards.

**Comment by akurzawa** [comment]
would be good, syspass stores login database, @nuxsmin can You make syspass to store logs in log file? from here is simple way to wrote custom filter for fail2ban

**Comment by nuxsmin** [comment]
Hi @akurzawa @wendelb , can you try the latest 2.0-beta version, it implements syslog and remote syslog features for every event logged in the event log.

**Comment by nuxsmin** [comment]
Hello, sysPass v3 has been released out and many features besides bugfixes have been implemented/solved.

Thanks for your contribution!

**Pull request closed without merging**
