### PR TITLE
Fix https checks behind reverse proxy

### PR DESCRIPTION
**Pull request by wseredynski**
Hi,
This fixes https check behind reverse proxy (copied from 1.2)

### CODE REVIEW

**Comment by nuxsmin** [comment]
Umm, I will need to perform some tests, because some reverse proxy environments does not encrypt the whole path, it would encrypt the client side but not the backend one, so the backend (sysPass webserver) would display that the connection is secured, but it isn't really. That is because I didn't implement that behavior...

**Comment by wseredynski** [comment]
We're using docker image as backend application. At the moment it seems it only listens on 80 port (according to vhost file) - I think this is fine as long as it's not exposed externally.

**Comment by nuxsmin** [comment]
What do you think about let it so?. I think that the user should be warned about the connection security status, because his data is being sent insecure on some part of the path.

**Comment by wseredynski** [comment]
Yes, you're right. I'll close this one.

**Comment by nuxsmin** [comment]
Thanks, let me know if you have any idea to improve it.

Kind regards

**Pull request closed without merging**
