### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by vmario89**
updated with Poedit - translation state = 100%

### CODE REVIEW

**Comment by vmario89** [comment]
sorry for the fucked up title of pull request. Just my first pull request tryouts with github^^

**Comment by nuxsmin** [comment]
Hello,

First of all thanks for your contribution!

I've reviewed the changes and you didn't translate BBDD (Spanish), which is database (DB) in English, so I think that it  has a German translation (Datenbank), doesn't it?

Could you add your name to X-Contributors meta tag?

Kind regards

**Comment by vmario89** [comment]
hey,

yes thats rights. With the phrase BBDD i was bit unsure so let in unchanged. But i can fix it quickly.
by the way i joined the official sysPass project on the POEdit web site to contribute. Need to be acknowledged to contribute.

**Comment by nuxsmin** [comment]
Great! I haven't mentioned POEdit because I thought you were comfortable using a desktop version ;) but I will accept your request tomorrow (writing on mobile...-no passwords here-) .

**Comment by vmario89** [comment]
i just uploaded a more recent po/mo version of german lang some seconds ago into my master repo of syspass fork.

hope you can see the new uploaded files.

i pushed the lang data into ms word 2017 too to find some more spelling mistakes (because i use the community free edition of POEdit).

btw i dont know if the web version of POEdit is better or not. Just let me give a try ^^

**Comment by nuxsmin** [comment]
Great! POEdit is a nice web app that makes translating easy and collaborative

**Pull request merged**
